In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("amazon_multi_keyword_results1.csv")
df.head()

,keyword,asin,title,price,rating,review_count,url
0,laptop,B0F196M26K,"acer Aspire 16 AI Copilot+ PC | 16"" WUXGA 120H...","EGP 36,836.76",4.3,NaN,https://www.amazon.com/sspa/click?ie=UTF8&spc=...
1,laptop,B0FYNTYRTL,"Lenovo V14 G5 Hybrid Work Laptop - 14"" FHD Dis...","EGP 31,574.29",4.1,NaN,https://www.amazon.com/sspa/click?ie=UTF8&spc=...
2,laptop,B0GR1JTFP8,Apple 2026 MacBook Air 13-inch Laptop with M5 ...,NaN,4.7,NaN,https://www.amazon.com/Apple-2026-MacBook-13-i...
3,laptop,B09R6FNNS1,Dell 15 Laptop DC15250-15.6-inch FHD 120Hz Dis...,NaN,4.3,NaN,https://www.amazon.com/Dell-DC15250-15-6-inch-...
4,laptop,B0947BJ67M,"HP 14 Laptop, Intel Celeron N4020, 4 GB RAM, 6...","EGP 10,259.19",4.0,NaN,https://www.amazon.com/HP-Micro-edge-Microsoft...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       9578 non-null   str
 1   asin          9578 non-null   str
 2   title         9578 non-null   str
 3   price         8486 non-null   str
 4   rating        9489 non-null   float64
 5   review_count  51 non-null     float64
 6   url           9578 non-null   str
dtypes: float64(2), str(5)
memory usage: 7.2 MB

In [4]:
df2 = pd.read_csv("amazon_multi_keyword_results2.csv")
df2.head()

,keyword,asin,title,price,rating,review_count,url
0,smart tv,B0DWHKF7V5,"Roku Smart TV – 55-Inch Select Series, 4K HDR ...",NaN,4.5,NaN,https://www.amazon.com/Roku-Smart-2025-Televis...
1,smart tv,B0DXN3T1GD,SAMSUNG 32-Inch Class Full HD F6000 Smart TV (...,"EGP 6,735.44",4.1,NaN,https://www.amazon.com/SAMSUNG-32-Inch-Object-...
2,smart tv,B0DXMWL3RW,Samsung 65-Inch Class Crystal UHD U8000F 4K Sm...,NaN,4.2,NaN,https://www.amazon.com/Samsung-65-Inch-Process...
3,smart tv,B0C1HZRXXN,TCL 32-Inch Class S3 1080p LED Smart TV with F...,"EGP 5,261.94",4.2,NaN,https://www.amazon.com/tcl-fire-tv-32-inch-cla...
4,smart tv,B0DXMY6KV8,Samsung 55-Inch Class QLED Q7F Series Samsung ...,NaN,4.3,NaN,https://www.amazon.com/Samsung-55-Inch-Trackin...

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 13019 entries, 0 to 13018
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       13019 non-null  str
 1   asin          13019 non-null  str
 2   title         13019 non-null  str
 3   price         12218 non-null  str
 4   rating        12852 non-null  float64
 5   review_count  6 non-null      float64
 6   url           13019 non-null  str
dtypes: float64(2), str(5)
memory usage: 10.0 MB

In [6]:
df3 = pd.read_csv("amazon_multi_keyword_results3.csv")
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 12747 entries, 0 to 12746
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       12747 non-null  str
 1   asin          12747 non-null  str
 2   title         12747 non-null  str
 3   price         12299 non-null  str
 4   rating        12627 non-null  float64
 5   review_count  23 non-null     float64
 6   url           12747 non-null  str
dtypes: float64(2), str(5)
memory usage: 9.8 MB

In [7]:
final_df = pd.concat([df, df2,df3], ignore_index=True)
final_df.drop_duplicates(subset=['asin'], keep='first', inplace=True)
final_df.info()

<class 'pandas.DataFrame'>
Index: 30122 entries, 0 to 35343
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       30122 non-null  str
 1   asin          30122 non-null  str
 2   title         30122 non-null  str
 3   price         27932 non-null  str
 4   rating        29762 non-null  float64
 5   review_count  66 non-null     float64
 6   url           30122 non-null  str
dtypes: float64(2), str(5)
memory usage: 22.6 MB